import java.nio.file.Path;
import java.time.LocalDateTime;

public class MediaItem {

    // This helps us know if the file is an image or a video
    public enum Type {
        IMAGE,
        VIDEO
    }

    // Path to the file (where it is located)
    private final Path path;

    // Type of file (image or video)
    private final Type type;

    // Date when the file was created or taken
    private LocalDateTime dateTime;

    // GPS information
    private Double latitude;
    private Double longitude;

    // Text description generated by the AI
    private String description;

    // Path to the generated audio file
    private Path audioPath;

    // Path to the generated video clip
    private Path clipPath;

    // Constructor: creates a media item with its file and type
    public MediaItem(Path path, Type type) {
        this.path = path;
        this.type = type;
    }

    // Returns the file path
    public Path getPath() {
        return path;
    }

    // Returns if it's image or video
    public Type getType() {
        return type;
    }

    // Returns the date
    public LocalDateTime getDateTime() {
        return dateTime;
    }

    // Sets the date
    public void setDateTime(LocalDateTime dateTime) {
        this.dateTime = dateTime;
    }

    // Returns latitude
    public Double getLatitude() {
        return latitude;
    }

    // Sets latitude
    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    // Returns longitude
    public Double getLongitude() {
        return longitude;
    }

    // Sets longitude
    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    // Checks if this item has GPS data
    public boolean hasGps() {
        return latitude != null && longitude != null;
    }

    // Returns the description generated by AI
    public String getDescription() {
        return description;
    }

    // Sets the description
    public void setDescription(String description) {
        this.description = description;
    }

    // Returns the path of the audio file
    public Path getAudioPath() {
        return audioPath;
    }

    // Sets the audio file path
    public void setAudioPath(Path audioPath) {
        this.audioPath = audioPath;
    }

    // Returns the video clip path
    public Path getClipPath() {
        return clipPath;
    }

    // Sets the video clip path
    public void setClipPath(Path clipPath) {
        this.clipPath = clipPath;
    }
}